// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmCtUMNPr7MHQ7NaVcfJzGw4onk4Jphp4',
    appId: '1:619236238957:web:36873bfddac6e3817d8164',
    messagingSenderId: '619236238957',
    projectId: 'fluttter-vcall',
    authDomain: 'fluttter-vcall.firebaseapp.com',
    storageBucket: 'fluttter-vcall.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvQSL-Wilqq3nWN_OxVSD_j_IEuWnoSVU',
    appId: '1:619236238957:android:e4c291efaa6ea9837d8164',
    messagingSenderId: '619236238957',
    projectId: 'fluttter-vcall',
    storageBucket: 'fluttter-vcall.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-kxLRMBCxFj6uS0TwbQw9GMLFekmWXAA',
    appId: '1:619236238957:ios:c3bb728ff250ddf17d8164',
    messagingSenderId: '619236238957',
    projectId: 'fluttter-vcall',
    storageBucket: 'fluttter-vcall.firebasestorage.app',
    iosBundleId: 'com.example.synpitarn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-kxLRMBCxFj6uS0TwbQw9GMLFekmWXAA',
    appId: '1:619236238957:ios:c3bb728ff250ddf17d8164',
    messagingSenderId: '619236238957',
    projectId: 'fluttter-vcall',
    storageBucket: 'fluttter-vcall.firebasestorage.app',
    iosBundleId: 'com.example.synpitarn',
  );
}
